### ISSUE TITLE
Really Good, but there is "No such module as RealmSwift"

### ISSUE THREAD

**Issue by Gudetamwa** [WaqarZahour/ToDo-App#2]
![Screen Shot 2020-01-01 at 3 53 27 PM](https://user-images.githubusercontent.com/59237254/71646033-fedc3f00-2cae-11ea-927b-e87ac07fef70.png)

I tried taking the module out entirely but that produces other errors. How can I get rid of this?

**Comment by WaqarZahour** [comment]
You have to open up the ToDoApp.xcworkspace and play it should work

**Comment by WaqarZahour** [comment]
> ![Screen Shot 2020-01-01 at 3 53 27 PM](https://user-images.githubusercontent.com/59237254/71646033-fedc3f00-2cae-11ea-927b-e87ac07fef70.png)
> 
> I tried taking the module out entirely but that produces other errors. How can I get rid of this?
You have to open up the ToDoApp.xcworkspace and then play it should work

**Comment by ekdysis** [comment]
@darkness101 Open up the app using ToDoApp.xcworkspace as @WaqarZahour mentioned or run a `pod install` from the root folder. You shouldn't encounter that error anymore.

**Comment by Gudetamwa** [comment]
yeah that worked, thx

**Comment by ekdysis** [comment]
@darkness101 Feel free to close this issue if you are able to run the project, thanks! 😀
